#!/bin/bash

#compile client programs that request encryption and decryption from daemon programs
gcc otp_enc.c -o otp_enc
gcc otp_dec.c -o otp_dec

#compile daemon programs that perform the encryption and decryption 
gcc otp_enc_d.c -o otp_enc_d
gcc otp_dec_d.c -o otp_dec_d

#compile key generator program
gcc keygen.c -o keygen
