fight: Tournament.o Barbarian.o BlueMen.o Creature.o HarryPotter.o inputVal.o main.o Medusa.o menu.o Vampire.o Queue.o
	g++ -std=c++0x -g  Tournament.o Barbarian.o BlueMen.o Creature.o HarryPotter.o inputVal.o main.o Medusa.o menu.o Vampire.o Queue.o -o project4

attackSeq.o: Tournament.cpp
	g++ -std=c++0x -c Tournament.cpp

Barbarian.o: Barbarian.cpp
	g++ -std=c++0x -c Barbarian.cpp

BlueMen.o: BlueMen.cpp
	g++ -std=c++0x -c BlueMen.cpp

Creature.o: Creature.cpp
	g++ -std=c++0x -c Creature.cpp

HarryPotter.o: HarryPotter.cpp
	g++ -std=c++0x -c HarryPotter.cpp

inputVal.o: inputVal.cpp
	g++ -std=c++0x -c inputVal.cpp

main.o: main.cpp
	g++ -std=c++0x -c main.cpp

Medusa.o: Medusa.cpp
	g++ -std=c++0x -c Medusa.cpp

menu.o: menu.cpp
	g++ -std=c++0x -c menu.cpp

Vampire.o: Vampire.cpp
	g++ -std=c++0x -c Vampire.cpp

Queue.o: Queue.cpp
	g++ -std=c++0x -c Queue.cpp

clean:
	rm *.o project4 
